# @package _global_

dm:
  source:
    fd: 1
    run_split_dist:
      dev: [1, 7]
      val: [2, 3]
      test: [6]
    first_time_to_predict: [ 1200, 140, 1050, 990, 2300, 1480, 1930 ]
  target:
    fd: 2
    run_split_dist:
      dev: [1, 2]
      val: [3, 4]
      test: [6]
    first_time_to_predict: [ 160, 210, 450, 200, 530, 340, 40 ]
  feature_extractor:
    feature_idx: [0, 1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 16, 17, 20, 21, 22, 23, 40, 41, 43, 44, 48, 50, 52, 54, 56, 57, 58, 59]
