# @package _global_

dann:
  dann_factor: 1.0
  lr: 0.01
  optim_weight_decay: 0.01

dm:
  batch_size: 256
  source:
    fd: 1
  target:
    fd: 4

domain_disc:
  dropout: 0.3
  units: [32, 1]

feature_extractor:
  fc_dropout: 0.7
  fc_units: 64
  dropout: 0.7
  units: [128]

regressor:
  dropout: 0.3
  units: [32, 32, 1]
